
GET https://ppmug1sihj.execute-api.us-east-1.amazonaws.com/prod/spaces
###

POST https://ppmug1sihj.execute-api.us-east-1.amazonaws.com/prod/spaces
content-type: application/json

 {
    "location": "Dublin",
    "name": "Best location"
 }
###

GET https://ppmug1sihj.execute-api.us-east-1.amazonaws.com/prod/spaces?id=8c88b1df-2558-4273-a986-0daa4256ce3c
###

DELETE https://ppmug1sihj.execute-api.us-east-1.amazonaws.com/prod/spaces?id=8c88b1df-2558-4273-a986-0daa4256ce3c
###

PUT https://ppmug1sihj.execute-api.us-east-1.amazonaws.com/prod/spaces?id=39e6a306-6d1c-4940-85d8-f28d47953182
content-type: application/json

 {
    "name": "Best location 5"
 }
###


